wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [40, 40]
    rows: [13, 13, 4]
  refreshInterval: 1
  mods:
    clocks:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Gdynia: "Europe/Warsaw"
        UCT: "UCT"
        India: "Asia/Kolkata"
        Eastern: "America/New_York"
        Pacific: "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
    security:
      enabled: true
      position:
        top: 1
        left: 0
        height: 1
        width: 1
      refreshInterval: 3600
    status:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      refreshInterval: 1

    cryptolive:
      colors:
        from:
          name: coral
          displayName: grey
        to:
          name: white
          price: green
      currencies:
        BTC:
          displayName: Bitcoin
          to:
            - USD
            - PLN
            - ETH
        ETH:
          displayName: Ethereum
          to:
            - USD
            - PLN
            - ETH
        BCC:
          displayName: Bitcoin Cash
          to:
            - USD
            - PLN
            - ETH
        LTC:
          displayName: Litecoin
          to:
            - USD
            - PLN
            - ETH
      enabled: true
      position:
        top: 0
        left: 1
        height: 2
        width: 1
      updateInterval: 60
